imap jj <esc>

inoremap jk <esc>
inoremap kj <esc>

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set number " Show line numbers
set ruler " Show position in file
set history=100

" show matching bracket
set showmatch
set incsearch
set hlsearch
" Pressing * will select a word and serch for it in a file
set ignorecase
set wildmenu  " show list instead of just completing
set wildmode=list:longest,full

set ai " Auto indent
set si " Smart indent
set wrap " Wrap lines

set cursorline
set autoread

let g:mapleader = ','
let mapleader = ','

nmap - $
xmap - $

" map space in normal mode to Search :)
nnoremap <space> /

nmap <enter> i<cr><esc>

" Surround word with STUFF
" mt - mark current position
" ciw - cut inner word and go to Inset Mode
" ( - type ( char
" <C-R>" - paste content of last buffor from yank or delete
" ) - type ) char
" <Esc>`t - escape and go to t mark
nmap z( mtcaW(<C-R>")<Esc>`t
nmap z[ mtcaW[<C-R>"]<Esc>`t
nmap z' mtciW'<C-R>"'<Esc>`t
nmap z" mtciw"<C-R>""<Esc>`t

" Insert empty line below / above
nnoremap zo mto<Esc>`t
nnoremap zO mtO<Esc>`t

nnoremap zj :join<CR>

" WINDOWS BINDINGS
" backspace in Visual mode deletes selection
vnoremap <BS> X

" CTRL-X and SHIFT-Del are Cut
vnoremap <C-X> "+x
vnoremap <S-Del> "+x

" CTRL-C and CTRL-Insert are Copy
vnoremap <C-C> "+y
vnoremap <C-Insert> "+y

" CTRL-V and SHIFT-Insert are Paste
map <C-V>		"+gp
map <S-Insert>		"+gp

cmap <C-V>		<C-R>+
cmap <S-Insert>		<C-R>+


" CTRL-A is Select all
noremap <C-A> gggH<C-O>G
inoremap <C-A> <C-O>gg<C-O>gH<C-O>G
cnoremap <C-A> <C-C>gggH<C-O>G
onoremap <C-A> <C-C>gggH<C-O>G
snoremap <C-A> <C-C>gggH<C-O>G
xnoremap <C-A> <C-C>ggVG

" CTRL-S is Save File
imap <C-S> <Esc>:w!<cr>a


" after going to next find , center the screen on the finding "
map N Nzz
map n nzz

" Close window"
nnoremap zx :wq<CR>
